/**
 * Copinex Compensation Engine — 90-Day Investment Packages
 *
 * Source: Investment Package spec (Henry, 2026-09-25).
 *
 * Rules implemented:
 *  1. Five tiers, selected by principal: $50–$499 → 10%/mo, $500–$999 → 11%/mo,
 *     $1,000–$1,999 → 12%/mo, $2,000–$4,999 → 13.5%/mo, $5,000+ → 15%/mo.
 *  2. First 90 days: daily profit accrues into the Withdrawal Wallet (LOCKED),
 *     withdrawable only after the 90-day settlement period ends (day 90).
 *  3. After day 90: profit is credited monthly; the original capital stays active
 *     and keeps earning indefinitely.
 *  4. An ADDITIONAL 20% of each account's monthly profit is paid to its upline
 *     chain as commission (compression applied, per the networking structure).
 *
 * Money rule: ALL values are integer cents. Daily profit uses floor() so the
 * sum of daily credits never exceeds the nominal monthly rate (no overpayment).
 */
import {
  AVAILABLE_AFTER_DAYS,
  COMPRESSION_STOP_AT_GEN,
  DAILY_ACCRUAL_DAYS,
  INVESTMENT_PACKAGES,
  UPLINE_COMMISSION_RATE_BPS,
  UPLINE_COMMISSION_SPLIT,
} from './constants.js';
import type {
  DailyCredit,
  InvestmentPackage,
  InvestmentSchedule,
  UplineCommissionPayout,
  UplineMember,
} from './types.js';

const DAY_MS = 86_400_000;

/** Add whole days to a date (UTC-normalized). */
export function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setUTCDate(d.getUTCDate() + days);
  return d;
}

/** Whole days from `from` to `to` (to - from, floored). */
export function daysBetween(from: Date, to: Date): number {
  const ms = Date.UTC(to.getUTCFullYear(), to.getUTCMonth(), to.getUTCDate()) -
    Date.UTC(from.getUTCFullYear(), from.getUTCMonth(), from.getUTCDate());
  return Math.floor(ms / DAY_MS);
}

/**
 * Select the investment tier for an amount, or null if the amount is outside
 * every tier (below $50). Tier 5 has no upper bound.
 */
export function getPackageForAmount(amountCents: number): InvestmentPackage | null {
  if (!Number.isInteger(amountCents) || amountCents <= 0) return null;
  return (
    INVESTMENT_PACKAGES.find(
      (p) =>
        amountCents >= p.minAmountCents &&
        (p.maxAmountCents === null || amountCents <= p.maxAmountCents),
    ) ?? null
  );
}

/** Daily profit for one day: floor(principal × dailyRate / 10000). */
export function computeDailyProfitCents(principalCents: number, dailyRateBps: number): number {
  if (!Number.isInteger(principalCents) || principalCents <= 0) {
    throw new Error(`computeDailyProfitCents: principal must be a positive integer, got ${principalCents}`);
  }
  if (!Number.isInteger(dailyRateBps) || dailyRateBps <= 0) {
    throw new Error(`computeDailyProfitCents: dailyRateBps must be a positive integer, got ${dailyRateBps}`);
  }
  return Math.floor((principalCents * dailyRateBps) / 10_000);
}

/** Monthly profit: floor(principal × monthlyRate / 10000). */
export function computeMonthlyProfitCents(principalCents: number, monthlyRateBps: number): number {
  if (!Number.isInteger(principalCents) || principalCents <= 0) {
    throw new Error(`computeMonthlyProfitCents: principal must be a positive integer, got ${principalCents}`);
  }
  if (!Number.isInteger(monthlyRateBps) || monthlyRateBps <= 0) {
    throw new Error(`computeMonthlyProfitCents: monthlyRateBps must be a positive integer, got ${monthlyRateBps}`);
  }
  return Math.floor((principalCents * monthlyRateBps) / 10_000);
}

/**
 * Build the earning schedule for an investment:
 *  - 90 daily credits (days 1–90), unlocking together after the 90-day
 *    settlement period (day 90);
 *  - the monthly profit amount credited each calendar month after day 90.
 */
export function buildInvestmentSchedule(
  principalCents: number,
  pkg: InvestmentPackage,
  startDate: Date,
): InvestmentSchedule {
  const daily = computeDailyProfitCents(principalCents, pkg.dailyRateBps);
  const monthly = computeMonthlyProfitCents(principalCents, pkg.monthlyRateBps);

  const dailyCredits: DailyCredit[] = Array.from({ length: DAILY_ACCRUAL_DAYS }, (_, i) => {
    const day = i + 1;
    return {
      day,
      amountCents: daily,
      creditedAt: addDays(startDate, day),
      availableAt: addDays(startDate, AVAILABLE_AFTER_DAYS),
    };
  });

  return { dailyCredits, monthlyProfitCents: monthly };
}

/**
 * The 20% commission pool generated by a profit credit.
 * floor() keeps the pool within the stated rate.
 */
export function computeUplineCommissionPoolCents(profitCents: number): number {
  if (!Number.isInteger(profitCents) || profitCents < 0) {
    throw new Error(`computeUplineCommissionPoolCents: profit must be a non-negative integer, got ${profitCents}`);
  }
  return Math.floor((profitCents * UPLINE_COMMISSION_RATE_BPS) / 10_000);
}

function weightBpsForLevel(level: number): number | null {
  switch (level) {
    case 1: return UPLINE_COMMISSION_SPLIT.directSponsor;
    case 2: return UPLINE_COMMISSION_SPLIT.gen2;
    case 3: return UPLINE_COMMISSION_SPLIT.gen3;
    case 4: return UPLINE_COMMISSION_SPLIT.gen4;
    case 5: return UPLINE_COMMISSION_SPLIT.gen5;
    case 6: return UPLINE_COMMISSION_SPLIT.gen6;
    default: return null;
  }
}

/**
 * Distribute the 20% commission pool across the investor's upline chain.
 *
 * Networking-structure rule (documented assumption): each generation level
 * 1–6 carries a fixed weight. Inactive members at a level are skipped
 * (compression, per §9.2); the pool is renormalized over the qualified levels
 * so exactly 100% of the pool is paid out. Remainder cents (from floor) go to
 * the closest qualified upline via largest-remainder allocation.
 *
 * @returns payouts summing EXACTLY to poolCents (or [] if no qualified upline).
 */
export function distributeUplineCommission(
  poolCents: number,
  chain: UplineMember[],
): UplineCommissionPayout[] {
  if (!Number.isInteger(poolCents) || poolCents < 0) {
    throw new Error(`distributeUplineCommission: poolCents must be a non-negative integer, got ${poolCents}`);
  }
  if (poolCents === 0) return [];

  // Compression: keep the first ACTIVE member at each level, up to gen 6.
  const qualified: { recipientId: string; level: number; weightBps: number }[] = [];
  for (let level = 1; level <= COMPRESSION_STOP_AT_GEN; level++) {
    const member = chain.find((m) => m.level === level && m.isActive);
    const weight = weightBpsForLevel(level);
    if (member && weight !== null) {
      qualified.push({ recipientId: member.userId, level, weightBps: weight });
    }
  }
  if (qualified.length === 0) return [];

  const weightSum = qualified.reduce((sum, q) => sum + q.weightBps, 0);

  // Renormalize weights to the pool, floor each share.
  const shares = qualified.map((q) => {
    const exact = (q.weightBps * poolCents) / weightSum;
    return { ...q, exact, base: Math.floor(exact) };
  });

  let remainder = poolCents - shares.reduce((sum, s) => sum + s.base, 0);

  // Largest-remainder: give leftover cents to the largest fractional shares.
  const order = shares
    .map((s, i) => ({ i, frac: s.exact - s.base }))
    .sort((a, b) => b.frac - a.frac);
  for (const { i } of order) {
    if (remainder <= 0) break;
    const share = shares[i];
    if (share) {
      share.base += 1;
      remainder -= 1;
    }
  }

  return shares.map((s) => ({ recipientId: s.recipientId, level: s.level, amountCents: s.base }));
}